project:
  type: website
  output-dir: docs

website:
  title: "Testing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  tools:
    - icon: github
      menu: 
        text: Source code
        url: https://github.com/USF-CMS-Fish-Ecology-Lab/GitHub-tutorial
     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



